### ISSUE TITLE
Please explain the variables (or provide documentation)

### ISSUE THREAD

**Issue by Husnain08** [interactionlab/unintended-input-dataset#1]
Dear Authors,
Thank you for providing us with these datasets. While I am reading these datasets, I am finding it difficult to interpret because of their structure. Moreover, there are no explanations of the variables involved in both of these datasets. Please provide us proper documentation for the variables of these datasets so that I could use them in my research.

Looking forward to hearing from you soon.
Best,
Muhammad Husnain

**Comment by Husnain08** [comment]
@huyvietle please look into it

**Comment by sven-mayer** [comment]
We now provided all the scrips which should solve all these problems.
